name: Go

on: [push]

   
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v -o ./reply-bot ./bot/cmd

    - name: Test
      run: go test -v -o ./reply-bot ./bot/cmd